export const createNewOrderPageDataProvider = {
  product: {
    sku: '182161M17700202',
  },
  customerAccount: {
    firstName: 'Auto',
    lastName: 'Test',
  },
  shippingAddressQuebec: {
    firstName: 'Auto',
    lastName: 'Test',
    company: 'Ssense',
    address: '333 Chabanel Ouest',
    city: 'Montreal',
    country: 'Canada',
    province: 'Quebec',
    postalCode: 'H2N 2G1',
    telephone: '5146005818',
  },
  billingAddressQuebec: {
    firstName: 'Auto',
    lastName: 'Test',
    company: 'Ssense',
    address: '333 Chabanel Ouest',
    city: 'Montreal',
    country: 'Canada',
    province: 'Quebec',
    postalCode: 'H2N 2G1',
    telephone: '5146005818',
  },
  shippingAddressBritishColumbia: {
    firstName: 'Auto',
    lastName: 'Test',
    company: 'Ssense',
    address: '4072 Robson St',
    city: 'Vancouver',
    country: 'Canada',
    province: 'BritishColumbia',
    postalCode: 'V6B 3K9',
    telephone: '6046015820',
  },
  billingAddressBritishColumbia: {
    firstName: 'Auto',
    lastName: 'Test',
    company: 'Ssense',
    address: '4072 Robson St',
    city: 'Vancouver',
    country: 'Canada',
    province: 'British Columbia',
    postalCode: 'V6B 3K9',
    telephone: '6046015820',
  },
  shippingAddressOntario: {
    firstName: 'Auto',
    lastName: 'Test',
    company: 'Ssense',
    address: '562 DryPineBay Rd',
    city: 'Copper Cliff',
    country: 'Canada',
    province: 'Ontario',
    postalCode: 'P0M 1N0',
    telephone: '7056829851',
  },
  billingAddressOntario: {
    firstName: 'Auto',
    lastName: 'Test',
    company: 'Ssense',
    address: '562 DryPineBay Rd',
    city: 'Copper Cliff',
    country: 'Canada',
    province: 'Ontario',
    postalCode: 'P0M 1N0',
    telephone: '7056829851',
  },
  shippingAddressSaskatchewan: {
    firstName: 'Auto',
    lastName: 'Test',
    company: 'Ssense',
    address: '333 Saskatchewan Chabanel Ouest',
    city: 'Saskatoon',
    country: 'Canada',
    province: 'Saskatchewan',
    postalCode: 'S7H 0A6',
    telephone: '5146005818',
  },
  billingAddressSaskatchewan: {
    firstName: 'Auto',
    lastName: 'Test',
    company: 'Ssense',
    address: '333 Saskatchewan Chabanel Ouest',
    city: 'Saskatoon',
    country: 'Canada',
    province: 'Saskatchewan',
    postalCode: 'S7H 0A6',
    telephone: '5146005818',
  },
  shippingAddressChina: {
    firstName: 'Auto',
    lastName: 'Test',
    company: 'Ssense',
    address: '123 Street',
    city: 'Beijing',
    country: 'China',
    province: 'Beijing',
    postalCode: '100005',
    telephone: '4721234567',
  },
  billingAddressChina: {
    firstName: 'Auto',
    lastName: 'Test',
    company: 'Ssense',
    address: '123 Street',
    city: 'Beijing',
    country: 'China',
    province: 'Beijing',
    postalCode: '100005',
    telephone: '4721234567',
  },
  shippingAddressUnitedKingdom: {
    firstName: 'Auto',
    lastName: 'Test',
    company: 'Ssense',
    address: '15 Fulwood Place',
    city: 'London',
    country: 'UnitedKingdom',
    province: 'UnitedKingdom',
    postalCode: 'WC1V 6AY',
    telephone: '441517097865',
  },
  billingAddressUnitedKingdom: {
    firstName: 'Auto',
    lastName: 'Test',
    company: 'Ssense',
    address: '15 Fulwood Place',
    city: 'London',
    country: 'UnitedKingdom',
    province: 'UnitedKingdom',
    postalCode: 'WC1V 6AY',
    telephone: '441517097865',
  },
  shippingAddressAlabama: {
    firstName: 'Auto',
    lastName: 'Test',
    company: 'Ssense',
    address: '333 Alabama Chabanel',
    city: 'Montgomery',
    country: 'UnitedStates',
    province: 'Alabama',
    postalCode: '36016',
    telephone: '5137776982',
  },
  billingAddressAlabama: {
    firstName: 'Auto',
    lastName: 'Test',
    company: 'Ssense',
    address: '333 Alabama Chabanel',
    city: 'Montgomery',
    country: 'UnitedStates',
    province: 'Alabama',
    postalCode: '36016',
    telephone: '5137776982',
  },
  shippingAddressCalifornia: {
    firstName: 'Auto',
    lastName: 'Test',
    company: 'Ssense',
    address: '333 California Chabanel',
    city: 'San Francisco',
    country: 'UnitedStates',
    province: 'California',
    postalCode: '94111',
    telephone: '5137776982',
  },
  billingAddressCalifornia: {
    firstName: 'Auto',
    lastName: 'Test',
    company: 'Ssense',
    address: '333 California Chabanel',
    city: 'San Francisco',
    country: 'UnitedStates',
    province: 'California',
    postalCode: '94111',
    telephone: '5137776982',
  },
  shippingAddressConnecticut: {
    firstName: 'Auto',
    lastName: 'Test',
    company: 'Ssense',
    address: '333 Connecticut Chabanel',
    city: 'Hartford',
    country: 'UnitedStates',
    province: 'Connecticut',
    postalCode: '06115',
    telephone: '5137776982',
  },
  billingAddressConnecticut: {
    firstName: 'Auto',
    lastName: 'Test',
    company: 'Ssense',
    address: '333 Connecticut Chabanel',
    city: 'Hartford',
    country: 'UnitedStates',
    province: 'Connecticut',
    postalCode: '06115',
    telephone: '5137776982',
  },
  shippingAddressDC: {
    firstName: 'Auto',
    lastName: 'Test',
    company: 'Ssense',
    address: '333 District of Columbia Chabanel',
    city: 'Washington',
    country: 'UnitedStates',
    province: 'DC',
    postalCode: '20026',
    telephone: '5137776982',
  },
  billingAddressDC: {
    firstName: 'Auto',
    lastName: 'Test',
    company: 'Ssense',
    address: '333 District of Columbia Chabanel',
    city: 'Washington',
    country: 'UnitedStates',
    province: 'DC',
    postalCode: '20026',
    telephone: '5137776982',
  },
  shippingAddressGeorgia: {
    firstName: 'Auto',
    lastName: 'Test',
    company: 'Ssense',
    address: '333 Georgia Chabanel',
    city: 'Montgomery',
    country: 'UnitedStates',
    province: 'Georgia',
    postalCode: '36016',
    telephone: '5137776982',
  },
  billingAddressGeorgia: {
    firstName: 'Auto',
    lastName: 'Test',
    company: 'Ssense',
    address: '333 Georgia Chabanel',
    city: 'Montgomery',
    country: 'UnitedStates',
    province: 'Georgia',
    postalCode: '36016',
    telephone: '5137776982',
  },
  shippingAddressHawaii: {
    firstName: 'Auto',
    lastName: 'Test',
    company: 'Ssense',
    address: '333 Hawaii Chabanel',
    city: 'Montgomery',
    country: 'UnitedStates',
    province: 'Hawaii',
    postalCode: '36016',
    telephone: '5137776982',
  },
  billingAddressHawaii: {
    firstName: 'Auto',
    lastName: 'Test',
    company: 'Ssense',
    address: '333 Hawaii Chabanel',
    city: 'Montgomery',
    country: 'UnitedStates',
    province: 'Hawaii',
    postalCode: '36016',
    telephone: '5137776982',
  },
  shippingAddressIllinois: {
    firstName: 'Auto',
    lastName: 'Test',
    company: 'Ssense',
    address: '2759 Star Route',
    city: 'Chicago',
    country: 'UnitedStates',
    province: 'Illinois',
    postalCode: '60654',
    telephone: '7086625053',
  },
  billingAddressIllinois: {
    firstName: 'Auto',
    lastName: 'Test',
    company: 'Ssense',
    address: '2759 Star Route',
    city: 'Chicago',
    country: 'UnitedStates',
    province: 'Illinois',
    postalCode: '60654',
    telephone: '7086625053',
  },
  shippingAddressIowa: {
    firstName: 'Auto',
    lastName: 'Test',
    company: 'Ssense',
    address: '333 Iowa Chabanel',
    city: 'Montgomery',
    country: 'UnitedStates',
    province: 'Iowa',
    postalCode: '36016',
    telephone: '5137776982',
  },
  billingAddressIowa: {
    firstName: 'Auto',
    lastName: 'Test',
    company: 'Ssense',
    address: '333 Iowa Chabanel',
    city: 'Montgomery',
    country: 'UnitedStates',
    province: 'Iowa',
    postalCode: '36016',
    telephone: '5137776982',
  },
  shippingAddressKentucky: {
    firstName: 'Auto',
    lastName: 'Test',
    company: 'Ssense',
    address: '333 Kentucky Chabanel',
    city: 'Montgomery',
    country: 'UnitedStates',
    province: 'Kentucky',
    postalCode: '36016',
    telephone: '5137776982',
  },
  billingAddressKentucky: {
    firstName: 'Auto',
    lastName: 'Test',
    company: 'Ssense',
    address: '333 Kentucky Chabanel',
    city: 'Montgomery',
    country: 'UnitedStates',
    province: 'Kentucky',
    postalCode: '36016',
    telephone: '5137776982',
  },
  shippingAddressLouisiana: {
    firstName: 'Auto',
    lastName: 'Test',
    company: 'Ssense',
    address: '333 Louisiana Chabanel',
    city: 'Montgomery',
    country: 'UnitedStates',
    province: 'Louisiana',
    postalCode: '36016',
    telephone: '5137776982',
  },
  billingAddressLouisiana: {
    firstName: 'Auto',
    lastName: 'Test',
    company: 'Ssense',
    address: '333 Louisiana Chabanel',
    city: 'Montgomery',
    country: 'UnitedStates',
    province: 'Louisiana',
    postalCode: '36016',
    telephone: '5137776982',
  },
  shippingAddressMaine: {
    firstName: 'Auto',
    lastName: 'Test',
    company: 'Ssense',
    address: '333 Maine Chabanel',
    city: 'Montgomery',
    country: 'UnitedStates',
    province: 'Maine',
    postalCode: '36016',
    telephone: '5137776982',
  },
  billingAddressMaine: {
    firstName: 'Auto',
    lastName: 'Test',
    company: 'Ssense',
    address: '333 Maine Chabanel',
    city: 'Montgomery',
    country: 'UnitedStates',
    province: 'Maine',
    postalCode: '36016',
    telephone: '5137776982',
  },
  shippingAddressMichigan: {
    firstName: 'Auto',
    lastName: 'Test',
    company: 'Ssense',
    address: '1245 D Street',
    city: 'Bloomfield Township',
    country: 'UnitedStates',
    province: 'Michigan',
    postalCode: '48302',
    telephone: '5863379695',
  },
  billingAddressMichigan: {
    firstName: 'Auto',
    lastName: 'Test',
    company: 'Ssense',
    address: '1245 D Street',
    city: 'Bloomfield Township',
    country: 'UnitedStates',
    province: 'Michigan',
    postalCode: '48302',
    telephone: '5863379695',
  },
  shippingAddressNebraska: {
    firstName: 'Auto',
    lastName: 'Test',
    company: 'Ssense',
    address: '333 Nebraska Chabanel',
    city: 'Montgomery',
    country: 'UnitedStates',
    province: 'Nebraska',
    postalCode: '36016',
    telephone: '5137776982',
  },
  billingAddressNebraska: {
    firstName: 'Auto',
    lastName: 'Test',
    company: 'Ssense',
    address: '333 Nebraska Chabanel',
    city: 'Montgomery',
    country: 'UnitedStates',
    province: 'Nebraska',
    postalCode: '36016',
    telephone: '5137776982',
  },
  shippingAddressNewYork: {
    firstName: 'Auto',
    lastName: 'Test',
    company: 'Ssense',
    address: '129 Gates Ave, Brooklyn',
    city: 'New York',
    country: 'UnitedStates',
    province: 'New York',
    postalCode: '11238',
    telephone: '5146005818',
    expectedTaxRate: 0.0888,
  },
  billingAddressNewYork: {
    firstName: 'Auto',
    lastName: 'Test',
    company: 'Ssense',
    address: '129 Gates Ave, Brooklyn',
    city: 'New York',
    country: 'UnitedStates',
    province: 'New York',
    postalCode: '11238',
    telephone: '5146005818',
  },
  shippingAddressNorthCarolina: {
    firstName: 'Auto',
    lastName: 'Test',
    company: 'Ssense',
    address: '333 North Carolina Chabanel',
    city: 'Montgomery',
    country: 'UnitedStates',
    province: 'North Carolina',
    postalCode: '36016',
    telephone: '5137776982',
  },
  billingAddressNorthCarolina: {
    firstName: 'Auto',
    lastName: 'Test',
    company: 'Ssense',
    address: '333 North Carolina Chabanel',
    city: 'Montgomery',
    country: 'UnitedStates',
    province: 'North Carolina',
    postalCode: '36016',
    telephone: '5137776982',
  },
  shippingAddressNorthDakota: {
    firstName: 'Auto',
    lastName: 'Test',
    company: 'Ssense',
    address: '333 North Dakota Chabanel',
    city: 'Montgomery',
    country: 'UnitedStates',
    province: 'North Dakota',
    postalCode: '36016',
    telephone: '5137776982',
  },
  billingAddressNorthDakota: {
    firstName: 'Auto',
    lastName: 'Test',
    company: 'Ssense',
    address: '333 North Dakota Chabanel',
    city: 'Montgomery',
    country: 'UnitedStates',
    province: 'North Dakota',
    postalCode: '36016',
    telephone: '5137776982',
  },
  shippingAddressOhio: {
    firstName: 'Auto',
    lastName: 'Test',
    company: 'Ssense',
    address: '3012 Round Table Drive',
    city: 'West Chester',
    country: 'UnitedStates',
    province: 'Ohio',
    postalCode: '45069',
    telephone: '5137776982',
  },
  billingAddressOhio: {
    firstName: 'Auto',
    lastName: 'Test',
    company: 'Ssense',
    address: '3012 Round Table Drive',
    city: 'West Chester',
    country: 'UnitedStates',
    province: 'Ohio',
    postalCode: '45069',
    telephone: '5137776982',
  },
  shippingAddressOklahoma: {
    firstName: 'Auto',
    lastName: 'Test',
    company: 'Ssense',
    address: '333 Oklahoma Chabanel',
    city: 'Montgomery',
    country: 'UnitedStates',
    province: 'Oklahoma',
    postalCode: '36016',
    telephone: '5137776982',
  },
  billingAddressOklahoma: {
    firstName: 'Auto',
    lastName: 'Test',
    company: 'Ssense',
    address: '333 Oklahoma Chabanel',
    city: 'Montgomery',
    country: 'UnitedStates',
    province: 'Oklahoma',
    postalCode: '36016',
    telephone: '5137776982',
  },
  shippingAddressSouthCarolina: {
    firstName: 'Auto',
    lastName: 'Test',
    company: 'Ssense',
    address: '333 South Carolina Chabanel',
    city: 'Montgomery',
    country: 'UnitedStates',
    province: 'South Carolina',
    postalCode: '36016',
    telephone: '5137776982',
  },
  billingAddressSouthCarolina: {
    firstName: 'Auto',
    lastName: 'Test',
    company: 'Ssense',
    address: '333 South Carolina Chabanel',
    city: 'Montgomery',
    country: 'UnitedStates',
    province: 'South Carolina',
    postalCode: '36016',
    telephone: '5137776982',
  },
  shippingAddressTennessee: {
    firstName: 'Auto',
    lastName: 'Test',
    company: 'Ssense',
    address: '333 Tennessee Chabanel',
    city: 'Montgomery',
    country: 'UnitedStates',
    province: 'Tennessee',
    postalCode: '36016',
    telephone: '5137776982',
  },
  billingAddressTennessee: {
    firstName: 'Auto',
    lastName: 'Test',
    company: 'Ssense',
    address: '333 Tennessee Chabanel',
    city: 'Montgomery',
    country: 'UnitedStates',
    province: 'Tennessee',
    postalCode: '36016',
    telephone: '5137776982',
  },
  shippingAddressTexas: {
    firstName: 'Auto',
    lastName: 'Test',
    company: 'Ssense',
    address: '333 Texas Chabanel',
    city: 'Montgomery',
    country: 'UnitedStates',
    province: 'Texas',
    postalCode: '36016',
    telephone: '5137776982',
  },
  billingAddressTexas: {
    firstName: 'Auto',
    lastName: 'Test',
    company: 'Ssense',
    address: '333 Texas Chabanel',
    city: 'Montgomery',
    country: 'UnitedStates',
    province: 'Texas',
    postalCode: '36016',
    telephone: '5137776982',
  },
  shippingAddressWestVirginia: {
    firstName: 'Auto',
    lastName: 'Test',
    company: 'Ssense',
    address: '333 West Virginia Chabanel',
    city: 'Montgomery',
    country: 'UnitedStates',
    province: 'West Virginia',
    postalCode: '36016',
    telephone: '5137776982',
  },
  billingAddressWestVirginia: {
    firstName: 'Auto',
    lastName: 'Test',
    company: 'Ssense',
    address: '333 West Virginia Chabanel',
    city: 'Montgomery',
    country: 'UnitedStates',
    province: 'West Virginia',
    postalCode: '36016',
    telephone: '5137776982',
  },
  shippingAddressWisconsin: {
    firstName: 'Auto',
    lastName: 'Test',
    company: 'Ssense',
    address: '333 Wisconsin Chabanel',
    city: 'Montgomery',
    country: 'UnitedStates',
    province: 'Wisconsin',
    postalCode: '36016',
    telephone: '5137776982',
  },
  billingAddressWisconsin: {
    firstName: 'Auto',
    lastName: 'Test',
    company: 'Ssense',
    address: '333 Wisconsin Chabanel',
    city: 'Montgomery',
    country: 'UnitedStates',
    province: 'Wisconsin',
    postalCode: '36016',
    telephone: '5137776982',
  },
  shippingAddressAustralia: {
    firstName: 'Auto',
    lastName: 'Test',
    company: 'Ssense',
    address: '333 Australian Chabanel',
    city: 'Melbourne',
    country: 'Australia',
    province: 'Victoria',
    postalCode: 'H2N AUD',
    telephone: '5137776982',
  },
  billingAddressAustralia: {
    firstName: 'Auto',
    lastName: 'Test',
    company: 'Ssense',
    address: '333 Australian Chabanel',
    city: 'Melbourne',
    country: 'Australia',
    province: 'Victoria',
    postalCode: 'H2N AUD',
    telephone: '5137776982',
  },
  shippingAddressJapan: {
    firstName: 'Auto',
    lastName: 'Test',
    company: 'Ssense',
    address: '333 Japanese Chabanel',
    city: 'Tokyo',
    country: 'Japan',
    province: 'Something',
    postalCode: 'H2N JPY',
    telephone: '5137776982',
  },
  billingAddressJapan: {
    firstName: 'Auto',
    lastName: 'Test',
    company: 'Ssense',
    address: '333 Japanese Chabanel',
    city: 'Tokyo',
    country: 'Japan',
    province: 'Something',
    postalCode: 'H2N JPY',
    telephone: '5137776982',
  },
  payment: {
    cardholdersName: 'Auto Test',
    // creditcardNumber: '4032039926075500',
    creditcardNumber: '4032030015905500',
    cvv: '123',
    expiryMonth: '09',
    expiryYear: '2020',
  },
};
