export const websiteCheckoutPageDataProvider = {
  productSize: {
    value1: '39/42_182115M22000101',
    value2: '43/46_182115M22000102',
  },
  shippingAddress: {
    firstName: 'AutoTest',
    lastName: 'Checkout',
    address: '900-333 Chabanel O',
    company: 'Ssense',
    city: 'Montreal',
    country: 'CA',
    province: 'QC',
    postalCode: 'H2N 2G1',
    telephone: '5146005818',
  },
  billingAddress: {
    firstName: 'AutoTest',
    lastName: 'Checkout',
    address: '900-333 Chabanel O',
    company: 'Ssense',
    city: 'Montreal',
    country: 'CA',
    province: 'QC',
    postalCode: 'H2N 2G1',
    telephone: '5146005818',
  },
  payment: {
    cardholdersName: 'Auto Test',
    cardNumber: '4032039926075500',
    cvv: '123',
    expiryMonth: '09',
    expiryYear: '2020',
  },
  sneakerProductDetailUrl:
    'https://qa.ssense.com/en-ca/men/product/gucci/white-ny-yankees-edition-rython-sneakers/3308129',
  shippingAddressNY: {
    firstName: 'AutoTest',
    lastName: 'Checkout',
    address: '129 Gates Ave, Brooklyn',
    company: 'Ssense',
    city: 'New York',
    country: 'US',
    province: 'NY',
    postalCode: '11238',
    telephone: '5146005818',
  },
  shippingAddressNH: {
    firstName: 'AutoTest',
    lastName: 'Checkout',
    address: '41 Green St',
    company: 'Ssense',
    city: 'Concord',
    country: 'US',
    province: 'NH',
    postalCode: '03301',
    telephone: '6032258610',
  },
  incorrectShippingAddress: {
    firstName: 'AutoTest',
    lastName: 'Checkout',
    address: 'Unexisting address',
    company: 'Ssense',
    city: 'Unexisting city',
    country: 'US',
    province: 'NY',
    postalCode: '99999',
    telephone: '5146005818',
  },
  taxRateData: {
    billingAddressNY: 0.08876,
    stateRateNY: 0.04,
  },
};
