export const createNewOrderPageAssertionData = {
  pageTitle: 'HQM | SSENSE',
  createOrderTitle: 'Create Order - HQM | SSENSE',
  masterOrderTitle: 'Master Order(manage) - HQM | SSENSE',
  masterOrderSearchTitle: 'Master Order - HQM | SSENSE',
  labelShippingCountry: 'Shipping Country',
  labelNoProduct: 'No product.',
  labelAddProduct: 'Add a product',
  labelSearch: 'Search',
  labelAddToCart: 'Add to Cart',
  labelProducts: 'Products',
  labelSearchCustomerAccount: 'Search Customer Account',
  labelCreateCustomerAccount: 'Create Customer Account',
  labelCustomerInfo: 'Customer Info',
  labelShipping: 'Shipping',
  labelBilling: 'Billing',
  labelSameAsShipping: 'Same as Shipping',
  labelAddresses: 'Addresses',
  labelShippingServices: 'Shipping Services',
  labelOrderSummary: 'Order Summary',
  labelPaymentProcessor: 'Payment Processor:',
  labelPayment: 'Payment',
  labelOrderConfirmation: 'Order Confirmation',
};
