export const navigationTestData = {
  WomensCategoryURL: 'https://qa.ssense.com/en-ca/women',
  homepageURL: 'https://qa.ssense.com/en-ca',
  langArray: ["'English'", "'Français'", "'日本語'", "'中文'"],
  BRAND_NAME_PARTIAL: 'Nik',
  BRAND_NAME1: 'Nike',
  BRAND_NAME2: 'Adidas',
  PRODUCT_SEARCH: 'SHOES',
  PRODUCT_NAME_4: '192751F128015',
  Story_4_data: '',
  PRODUCT_NAME_3: '192751F045002',
  TYPO_PRODUCT_SEARCH: 'gucki',
  INCOMPLETE_PRODUCT_SEARCH: 'gu',
  CORRECT_PRODUCT_NAME: 'Gucci',
  AVAILABLE_PRODUCT: '201011M220165',
  AVAILABLE_PROD_SIZE: '44_192451M18000201',
  SIZE_COMBO: ['9', '42'],
  lang_array: ['English', 'Français', '日本語', '中文'],
};
